cc_test(
    name = "utils_test",
    srcs = ["utils_test.cpp"],
    deps = [
        "//applications/object_detection_evaluator:utils",
        "//applications/object_detection_evaluator/proto:metrics",
        "@gtest//:main",
    ],
)
