FROM ubuntu:16.04

RUN apt-get update
RUN apt-get install -y ca-certificates

ADD ./teleop-server /teleop-server

EXPOSE 8000

ENTRYPOINT ./teleop-server --config /configs/config.json --secrets /secrets/secrets.json
