FROM node:7.10

# Base dependencies
RUN wget https://storage.googleapis.com/golang/go1.8.3.linux-amd64.tar.gz
RUN tar -C /usr/local -xzf go1.8.3.linux-amd64.tar.gz && rm go1.8.3.linux-amd64.tar.gz
RUN echo "export GOPATH=/go" >> /etc/profile
ENV GOPATH /go
RUN echo "export PATH=$PATH:/usr/local/go/bin:$GOPATH/bin" >> /etc/profile
ENV PATH $PATH:/usr/local/go/bin:$GOPATH/bin

RUN mkdir -p /go/src/github.com/zippyai/zippy/frontend && mkdir /go/src/github.com/zippyai/zippy/backend
WORKDIR /go/src/github.com/zippyai/zippy

COPY ["backend/Makefile", "/go/src/github.com/zippyai/zippy/backend"]
COPY ["frontend/package.json", "frontend/yarn.lock", "/go/src/github.com/zippyai/zippy/frontend/"]


RUN cd backend && make deps
RUN cd frontend && npm install && yarn install
