apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: cadvisor
  name: cadvisor
spec:
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: cadvisor
    spec:
      containers:
      - image: sha1/cadvisor
        name: cadvisor
        ports:
        - containerPort: 8080
          hostPort: 8080
        resources: {}
        volumeMounts:
        - mountPath: /rootfs
          name: cadvisor-claim0
        - mountPath: /var/run
          name: cadvisor-claim1
        - mountPath: /sys
          name: cadvisor-claim2
        - mountPath: /var/lib/docker
          name: cadvisor-claim3
      volumes:
      - name: cadvisor-claim0
        hostPath:
          path: /
          type: Directory
      - name: cadvisor-claim1
        hostPath:
          path: /var/run
          type: Directory
      - name: cadvisor-claim2
        hostPath:
          path: /sys
          type: Directory
      - name: cadvisor-claim3
        hostPath:
          path: /var/lib/docker
          type: Directory
status:
  currentNumberScheduled: 0
  desiredNumberScheduled: 0
  numberMisscheduled: 0
  numberReady: 3
