version: '2'

networks:
  monitor-net:
    driver: bridge

volumes:
    prometheus_data: {}
    grafana_data: {}
    push_persist: {}

services:

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '-config.file=/etc/prometheus/prometheus.yml'
      - '-storage.local.path=/prometheus'
      - '-alertmanager.url=http://alertmanager:9093'
      - '-storage.local.memory-chunks=100000'
    restart: unless-stopped
    expose:
      - 9090
    ports:
      - 9090:9090
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"
  
  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    volumes: 
      - ./alertmanager/:/etc/alertmanager/
    command:
      - '-config.file=/etc/alertmanager/config.yml'
      - '-storage.path=/alertmanager'
    restart: unless-stopped
    expose:
      - 9093
    ports:
      - 9093:9093
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"

  nodeexporter:
    image: prom/node-exporter
    container_name: nodeexporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '-collector.procfs=/host/proc'
      - '-collector.sysfs=/host/sys'
      - '-collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    restart: unless-stopped
    expose:
      - 9100
    ports:
      - 9100:9100
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"

  cadvisor:
    image: sha1/cadvisor
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    restart: unless-stopped
    expose:
      - 8080
    ports:
      - 8080:8080
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"
  
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
    env_file:
      - user.config
    restart: unless-stopped
    expose:
      - 3000
    ports:
      - 3000:3000
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"

  redis:
    image: oliver006/redis_exporter
    container_name: redis_exporter
    command: 
      - '--redis.addr=teleop-server-test.mxpas0.0001.usw2.cache.amazonaws.com:6379'
    restart: unless-stopped
    expose: 
      - 9121
    ports:
      - 9121:9121
    networks:
      - monitor-net

  postgres:
    image: wrouesnel/postgres_exporter
    container_name: postgres_exporter
    environment:
      - 'DATA_SOURCE_NAME=postgresql://{{db_user}}:{{db_pass}}@teleop-rds-test.cbvrnosnnm3s.us-west-2.rds.amazonaws.com:5432/{{db_name}}'
    restart: unless-stopped
    expose:
      - 9187
    ports:
      - 9187:9187
    networks:
      - monitor-net

  pushgateway:
    image: prom/pushgateway:v0.4.0
    container_name: push_gateway
    volumes:
      - push_persist:/data/persist
    command:
      - '-persistence.file=/data/persist/backup'
    restart: unless-stopped
    expose:
      - 9091
    ports:
      - 9091:9091
    networks:
      - monitor-net
