global:
  scrape_interval:     15s
  evaluation_interval: 15s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'docker-host-alpha'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - "targets.rules"
  - "hosts.rules"
  - "containers.rules"

# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:
  - job_name: 'nodeexporter'
    scrape_interval: 5s
    ec2_sd_configs:
      - region: us-west-2
        port: 9100
    relabel_configs:
        # Only monitor instances which have a tag called Monitoring "Monitoring"
      - source_labels: [__meta_ec2_tag_Monitoring]
        regex: On
        action: keep
    static_configs:
      - targets: ['nodeexporter:9100']

  - job_name: 'productionexporter'
    scrape_interval: 5s
    ec2_sd_configs:
      - region: us-west-2
        port: 9110
    relabel_configs:
        # Only monitor instances which have a tag called Monitoring "Monitoring"
      - source_labels: [__meta_ec2_tag_Monitoring]
        regex: On
        action: keep
    static_configs:
      - targets: ['productionexporter:9110']

  - job_name: 'cadvisor'
    scrape_interval: 5s
    ec2_sd_configs:
      - region: us-west-2
        port: 8080
    relabel_configs:
        # Only monitor instances which have a tag called Monitoring "Monitoring"
      - source_labels: [__meta_ec2_tag_Monitoring]
        regex: On
        action: keep
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['172.30.0.27:9090']

  - job_name: 'redis'
    scrape_interval: 10s
    static_configs:
      - targets: ['172.30.0.27:9121']

  - job_name: 'postgres'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9187']

  - job_name: 'ian-vehicle-exporter'
    static_configs:
      - targets: ['192.168.36.174:9000']

  - job_name: 'leland-teleop-exporter'
    static_configs:
      - targets: ['192.168.36.165:9110']

    - job_name: 'push-gateway'
    honor_labels: true
    static_configs:
      - targets: ['localhost:9091']


