#!/bin/bash

#
# Warning: running this on linux will change ownership of files to the user
# under which the docker daemon is running.
#

docker pull zippyai/clang-format

docker run \
	--rm \
	-it \
	-v "$(pwd):/zippy" \
	-e CFORMATTER="clang-format-3.8" \
	zippyai/clang-format \
		script/fix-code-formatting $*
