cc_test(
    name = "test",
    srcs = [
        "control_test.cpp",
    ],
    deps = [
        "//external:gflags",
        "//external:glog",
        "//samples/vehicle_command_to_motor_control",
        "@gtest//:main",
    ],
)
