/*
 * events.h
 *
 *  Created on: May 24, 2017
 *      Author: addaon
 */

#ifndef EVENTS_H_
#define EVENTS_H_

// NOTE: This file, and the various autogenerated header files (main.h, stm*.h, usb*.h) are the only
// C-clean header files in the system. All others (motor.h, servo.h, etc) are intended to be included
// from C++ code only.

#include <stdint.h>

#ifdef __cplusplus
 extern "C" {
#endif

// Dynamic configuration is done in main()
struct CommandHandlerConfiguration {
	struct MotorConfiguration {
		int reverse_direction;  // should be true if motor wire comes out the left of the fork
		float offset_x, offset_y;  // x is positive to the right, y is positive in front of the robot
	} motors[3];
};

// Event entry points
void OnStartup();
void OnInitialization(struct CommandHandlerConfiguration const *config);
void OnMainLoop();
void OnProcessorTick();
void OnHallSensorTransitionInterrupt();
void OnUSBReceive(uint8_t* Buf, uint32_t *Len);

#ifdef __cplusplus
}
#endif

#ifdef __cplusplus
// Includes needed for global variables only
#include "packages/core/proto/timestamp.nanopb.h"
// Global variables intended from use from C++ code only
extern class CommandHandler *command_handler;
extern volatile core_SystemTimestamp current_timestamp;  // TODO: Move this to a high res clock, currently 1 ms resolution
#endif

#endif /* EVENTS_H_ */
