cc_binary(
    name = "stereo_tracking_demo",
    srcs = ["stereo_tracking_demo.cpp"],
    deps = [
        "//packages/feature_detectors",
        "//packages/feature_tracker",
        "//packages/net",
        "//packages/utilities/opencv:opencv_utilities",
        "//packages/videoviewer:libvideoviewer",
    ],
)
