FROM nvidia/cuda:8.0-cudnn7-devel

# Bring in the preparation scripts separately. This is a kinda-sorta
# optimization: if these haven't changed, we will already have a cached image
# available to us as a starting point which should speed things up significantly.
ADD ./script/build/for_build_image /dockerbuildscripts

RUN cat /etc/*release && \
    /dockerbuildscripts/prepare_machine.sh && \
    /dockerbuildscripts/install_tensorflow.sh && \
    ldconfig

# Copy ZeroMQ headers to the container
COPY thirdparty/cppzmq /usr/local/cppzmq
RUN bazel version
